server:
  port: 3000
spring:  application:    name: atguigu-crowd-redis
  redis:    host: 192.168.31.135
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka