server:
  port: 4000
## 网关地址（自定义）
service-url:
  gatewayUrl: http://localhost
spring:
  application:
    name: atguigu-crowd-auth
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 192.168.31.135
  ## spring session设置
  session:
    store-type: redis
## eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
## 发短信配置
short:
  message:
    app-code: 61f2eaa3c43e42ad82c26fbbe1061311
    host: https://feginesms.market.alicloudapi.com
    method: GET
    path: /codeNotice
    sign: 151003
    skin: 84683 
## 配置ribbon超时时间
ribbon:
  ReadTimeout: 10000 
  ConnectTimeout: 10000
