server:
  port: 80
 
spring:
  application:
    name: atguigu-crowd-zuul 
  redis:
    host: 192.168.31.135
  ## spring session设置
  session:
    store-type: redis
## eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
## zuul
zuul:
  ignored-services: "*"
  sensitive-headers: "*"  # 在Zuul向其他微服务重定向时保持原本头信息（请求头、响应头 ${session.message}）
  routes:
    crowd-portal:
      service-id: atguigu-crowd-auth
      path: /** # 这里一定要使用两个“*”号，不然“/”路径后面的多层路径将无法访问
    crowd-project:
      service-id: atguigu-crowd-project
      path: /project/**
    crowd-order:
      service-id: atguigu-crowd-order
      path: /order/**
    crowd-pay:
      service-id: atguigu-crowd-pay
      path: /pay/**
## 配置ribbon超时时间
ribbon:
  ReadTimeout: 10000 
  ConnectTimeout: 10000